version: "2"
services:
  huntflow-reloaded-server:
    image: huntflow-reloaded-server
    network_mode: "host"
    environment:
    - CHANNEL_NAME=${CHANNEL_NAME}
    - LOGLEVEL=${LOGLEVEL}
    - LOG_FILE=${LOG_FILE}
    - POSTGRES_DBNAME=${POSTGRES_DBNAME}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_USER=${POSTGRES_USER}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_PORT=${REDIS_PORT}
    - TZ=${TZ}
  postgres-hf:
    network_mode: "host"
    image: postgres:11
    environment:
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_PORT=${POSTGRES_PORT}
    - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - /srv/postgres-hf-data:/var/lib/postgresql/data
  redis:
    image: cusdeb/redis:5.0-amd64
    network_mode: "host"
    environment:
    - REDIS_CONF_bind=127.0.0.1
    - REDIS_CONF_port=16379
